Add workaround for missing configs error
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 8).
For kernel requirements at matrix level 8, Kernel config errors:
    Missing config CONFIG_CFI_CLANG
    Missing config CONFIG_SHADOW_CALL_STACK